import com.fl3sc0b.whitechapelai.board._

/**
 * Example of main class
 */
object whitechapelai extends App {
  println("Welcome to whitechapelai !!")
  println("///////////////////////////")

  val listSquares = List[SquareBox](
    new SquareBox("", "", false, List("24"), 1),
    new SquareBox(id = "","",false, List("6"), 2),
    new SquareBox(id = "","",false, List("1", "7"), 1),
    new SquareBox(id = "","",false, List("1", "26"), 1),
    new SquareBox(id = "","",false, List("2"), 2),
    new SquareBox(id = "","",false, List("2", "3"), 1),
    new SquareBox(id = "","",false, List("3", "4", "5"), 0),
    new SquareBox(id = "","",false, List("5"), 2),
    new SquareBox(id = "","",false, List("15"), 2),
    new SquareBox(id = "","",false, List("16", "17"), 1),
    new SquareBox(id = "","",false, List("17", "18"), 1),
    new SquareBox(id = "","",false, List("18"), 1),
    new SquareBox(id = "","",false, List("19", "20"), 1),
    new SquareBox(id = "","",false, List("20", "40"), 1),
    new SquareBox(id = "","",false, List("41"), 2),
    new SquareBox(id = "","",false, List("21"), 2),
    new SquareBox(id = "","",false, List("21"), 1),
    new SquareBox(id = "","",false, List("23"), 1),
    new SquareBox(id = "","",false, List("6", "24", "25"), 1),
    new SquareBox(id = "","",false, List("7", "26"), 2),
    new SquareBox(id = "","",false, List("9"), 2),
    new SquareBox(id = "","",false, List("9", "11"), 1),
    new SquareBox(id = "","",false, List("4", "11", "12"), 1),
    new SquareBox(id = "","",false, List("12", "13"), 1),
    new SquareBox(id = "","",false, List("8", "26", "28"), 1),
    new SquareBox(id = "","",false, List("8", "9", "10"), 0),
    new SquareBox(id = "","",false, List("10", "30"), 1),
    new SquareBox(id = "","",false, List("30"), 1),
    new SquareBox(id = "","",false, List("13", "14", "32"), 1),
    new SquareBox(id = "","",false, List("24", "25"), 1),
    new SquareBox(id = "","",false, List("25", "44"), 1),
    new SquareBox(id = "","",false, List("26", "27", "44"), 1),
    new SquareBox(id = "","",false, List("27", "28"), 1),
    new SquareBox(id = "","",false, List("43"), 1),
    new SquareBox(id = "","",false, List("44"), 3),
    new SquareBox(id = "","",false, List("44", "46"), 2),
    new SquareBox(id = "","",false, List("46", "48"), 3),
    new SquareBox(id = "","",false, List("29"), 1),
    new SquareBox(id = "","",true, List("29", "30", "50"), 1),
    new SquareBox(id = "","",false, List("31", "50"), 1),
    new SquareBox(id = "","",false, List("31", "32"), 2),
    new SquareBox(id = "","",false, List("14", "33", "54"), 1),
    new SquareBox(id = "","",false, List("15", "33", "34"), 1),
    new SquareBox(id = "","",false, List("16", "35", "36"), 1),
    new SquareBox(id = "","",false, List("17", "36", "38"), 1),
    new SquareBox(id = "","",false, List("18", "19", "39"), 0),
    new SquareBox(id = "","",false, List("42"), 1),
    new SquareBox(id = "","",false, List("43"), 1),
    new SquareBox(id = "","",false, List("44", "59"), 2),
    new SquareBox(id = "","",false, List("45", "46", "47"), 1),
    new SquareBox(id = "","",false, List("48", "49"), 1),
    new SquareBox(id = "","",false, List("49", "50"), 2),
    new SquareBox(id = "","",false, List("31", "52"), 0),
    new SquareBox(id = "","",false, List("59", "60"), 1),
    new SquareBox(id = "","",false, List("60"), 1),
    new SquareBox(id = "","",false, List("79"), 1),
    new SquareBox(id = "","",false, List("45", "47", "61"), 1),
    new SquareBox(id = "","",false, List("47", "61"), 1),
    new SquareBox(id = "","",false, List("48", "62"), 1),
    new SquareBox(id = "","",false, List("63", "64"), 2),
    new SquareBox(id = "","",false, List("64", "66"), 1),
    new SquareBox(id = "","",false, List("51", "52"), 1),
    new SquareBox(id = "","",false, List("52", "54"), 1),
    new SquareBox(id = "","",true, List("34", "55"), 2),
    new SquareBox(id = "","",false, List("35", "37"), 1),
    new SquareBox(id = "","",false, List("37", "38", "39"), 0),
    new SquareBox(id = "","",false, List("39", "56"), 0),
    new SquareBox(id = "","",true, List("40", "57"), 2),
    new SquareBox(id = "","",false, List("41", "42", "58"), 1),
    new SquareBox(id = "","",false, List("22", "42"), 0),
    new SquareBox(id = "","",false, List("22", "23"), 1),
    new SquareBox(id = "","",false, List("95"), 2),
    new SquareBox(id = "","",false, List("78", "79"), 1),
    new SquareBox(id = "","",false, List("95"), 2),
    new SquareBox(id = "","",false, List("78", "96"), 1),
    new SquareBox(id = "","",false, List("78", "79", "80", "97"), 0),
    new SquareBox(id = "","",false, List("62", "80", "82"), 1),
    new SquareBox(id = "","",false, List("63", "65", "82"), 1),
    new SquareBox(id = "","",false, List("65", "66"), 2),
    new SquareBox(id = "","",false, List("51", "67"), 1),
    new SquareBox(id = "","",false, List("52", "53", "67"), 0),
    new SquareBox(id = "","",false, List("53", "54"), 2),
    new SquareBox(id = "","",false, List("68"), 1),
    new SquareBox(id = "","",false, List("84"), 1),
    new SquareBox(id = "","",false, List("112", "113"), 1),
    new SquareBox(id = "","",false, List("96", "114"), 1),
    new SquareBox(id = "","",false, List("96", "97"), 1),
    new SquareBox(id = "","",false, List("80", "81"), 0),
    new SquareBox(id = "","",false, List("98"), 1),
    new SquareBox(id = "","",false, List("65", "83"), 1),
    new SquareBox(id = "","",false, List("81", "118"), 0),
    new SquareBox(id = "","",false, List("112", "135"), 1),
    new SquareBox(id = "","",false, List("113", "114"), 2),
    new SquareBox(id = "","",false, List("114", "115", "137"), 0),
    new SquareBox(id = "","",false, List("115", "116"), 1),
    new SquareBox(id = "","",false, List("97", "117"), 0),
    new SquareBox(id = "","",false, List("135", "136", "148"), 1),
    new SquareBox(id = "","",false, List("137", "138"), 1),
    new SquareBox(id = "","",false, List("148", "162"), 1),
    new SquareBox(id = "","",false, List("136", "149"), 1),
    new SquareBox(id = "","",false, List("116"), 1),
    new SquareBox(id = "","",false, List("117"), 1),
    new SquareBox(id = "","",false, List("98"), 1),
    new SquareBox(id = "","",false, List("83"), 1),
    new SquareBox(id = "","",false, List("84"), 1),
    new SquareBox(id = "","",false, List("148", "149"), 1),
    new SquareBox(id = "","",false, List("162", "163"), 1),
    new SquareBox(id = "","",false, List("163", "174"), 2),
    new SquareBox(id = "","",false, List("138", "164"), 2),
    new SquareBox(id = "","",true, List("139", "164"), 1),
    new SquareBox(id = "","",false, List("139", "150"), 3),
    new SquareBox(id = "","",false, List("118"),3),
    new SquareBox(id = "","",true, List("118", "119", "120"), 2),
    new SquareBox(id = "","",false, List("99", "100", "120"), 1),
    new SquareBox(id = "","",false, List("99"), 2),
    new SquareBox(id = "","",false, List("100"), 2),
    new SquareBox(id = "","",false, List("85", "86"), 1),
    new SquareBox(id = "","",false, List("68", "86"), 2),
    new SquareBox(id = "","",false, List("55"), 2),
    new SquareBox(id = "","",false, List("56"), 1),
    new SquareBox(id = "","",false, List("56", "57"), 0),
    new SquareBox(id = "","",false, List("164", "174"), 2),
    new SquareBox(id = "","",false, List("150"), 2),
    new SquareBox(id = "","",false, List("151"), 1),
    new SquareBox(id = "","",false, List("151"), 2),
    new SquareBox(id = "","",false, List("151", "153"), 2),
    new SquareBox(id = "","",false, List("119", "121"), 1),
    new SquareBox(id = "","",false, List("121"), 1),
    new SquareBox(id = "","",false, List("121"), 2),
    new SquareBox(id = "","",false, List("122", "123"), 1),
    new SquareBox(id = "","",false, List("100", "122"), 2),
    new SquareBox(id = "","",false, List("123", "125"), 4),
    new SquareBox(id = "","",false, List("124"), 2),
    new SquareBox(id = "","",false, List("124"), 1),
    new SquareBox(id = "","",false, List("85", "101", "126"), 1),
    new SquareBox(id = "","",false, List("69", "102"), 1),
    new SquareBox(id = "","",false, List("69", "70", "103"), 0),
    new SquareBox(id = "","",false, List("70", "71", "87"), 0),
    new SquareBox(id = "","",false, List("71", "72", "88"), 0),
    new SquareBox(id = "","",false, List("72", "73", "74"), 1),
    new SquareBox(id = "","",false, List("58", "73"), 1),
    new SquareBox(id = "","",false, List("74", "75", "76"), 1),
    new SquareBox(id = "","",false, List("58", "73"), 1),
    new SquareBox(id = "","",false, List("76", "77"), 1),
    new SquareBox(id = "","",false, List("77"), 1),
    new SquareBox(id = "","",false, List("125", "126"), 1),
    new SquareBox(id = "","",false, List("143"), 3),
    new SquareBox(id = "","",true, List("101", "126"), 2),
    new SquareBox(id = "","",false, List("102", "127", "143"), 1),
    new SquareBox(id = "","",false, List("69", "127"), 0),
    new SquareBox(id = "","",false, List("103", "127", "128"), 0),
    new SquareBox(id = "","",false, List("128", "143", "144"), 1),
    new SquareBox(id = "","",false, List("129", "144", "145"), 1),
    new SquareBox(id = "","",false, List("104", "129"), 1),
    new SquareBox(id = "","",false, List("87"), 1),
    new SquareBox(id = "","",false, List("104", "145"), 0),
    new SquareBox(id = "","",false, List("71", "104"), 0),
    new SquareBox(id = "","",true, List("130", "145"), 2),
    new SquareBox(id = "","",false, List("104", "105", "130"), 1),
    new SquareBox(id = "","",false, List("88"), 1),
    new SquareBox(id = "","",false, List(""), 3),
    new SquareBox(id = "","",false, List("89", "90"), 1),
    new SquareBox(id = "","",false, List("75", "90"), 2),
    new SquareBox(id = "","",false, List("94"), 2),
    new SquareBox(id = "","",false, List("89", "91"), 1),
    new SquareBox(id = "","",false, List("91", "92", "93"), 1),
    new SquareBox(id = "","",false, List("93", "94"), 1),
    new SquareBox(id = "","",false, List("105", "106", "107"), 1),
    new SquareBox(id = "","",false, List("92", "107", "109"), 1),
    new SquareBox(id = "","",false, List("109"), 2),
    new SquareBox(id = "","",false, List("106", "108"), 1),
    new SquareBox(id = "","",false, List("108", "110", "132"), 1),
    new SquareBox(id = "","",false, List("110", "111"), 1),
    new SquareBox(id = "","",false, List("131"), 2),
    new SquareBox(id = "","",false, List("132", "133", "134"), 1),
    new SquareBox(id = "","",false, List("111", "134", "147"), 0),
    new SquareBox(id = "","",false, List("131", "146"), 1),
    new SquareBox(id = "","",false, List("133", "146", "147"), 0),
    new SquareBox(id = "","",false, List("188"), 2),
    new SquareBox(id = "","",false, List("175"), 2),
    new SquareBox(id = "","",false, List("188"), 2),
    new SquareBox(id = "","",false, List("175"), 1),
    new SquareBox(id = "","",false, List("190"), 1),
    new SquareBox(id = "","",false, List("176"), 2),
    new SquareBox(id = "","",false, List("166", "176"), 1),
    new SquareBox(id = "","",false, List("178", "189"), 1),
    new SquareBox(id = "","",false, List("165", "177"), 1),
    new SquareBox(id = "","",false, List("190", "191"), 1),
    new SquareBox(id = "","",false, List("177", "178"), 1),
    new SquareBox(id = "","",false, List("165", "167"), 2),
    new SquareBox(id = "","",false, List("152", "166"), 1),
    new SquareBox(id = "","",false, List("167", "178", "179"), 0),
    new SquareBox(id = "","",false, List("180 ", "191"), 1),
    new SquareBox(id = "","",false, List("168", "180"), 1),
    new SquareBox(id = "","",false, List("152", "153"), 2),
    new SquareBox(id = "","",false, List("169", "181"), 1),
    new SquareBox(id = "","",false, List("154", "168", "169", "170"), 0),
    new SquareBox(id = "","",false, List("140", "154"), 1),
    new SquareBox(id = "","",false, List("170", "181"), 1),
    new SquareBox(id = "","",false, List("141", "170"), 1),
    new SquareBox(id = "","",false, List("140"), 2),
    new SquareBox(id = "","",false, List("155", "182"), 1),
    new SquareBox(id = "","",false, List("141", "155"), 1),
    new SquareBox(id = "","",false, List("182", "183", "192"), 1),
    new SquareBox(id = "","",false, List("171", "183"), 1),
    new SquareBox(id = "","",false, List(""), 2),
    new SquareBox(id = "","",false, List("156", "157"), 1),
    new SquareBox(id = "","",false, List("142", "156"), 1),
    new SquareBox(id = "","",false, List("184", "192"), 1),
    new SquareBox(id = "","",false, List("183", "184"), 2),
    new SquareBox(id = "","",false, List("183", "185"), 1),
    new SquareBox(id = "","",false, List("193", "194"), 1),
    new SquareBox(id = "","",false, List("186", "193"), 1),
    new SquareBox(id = "","",false, List("185"), 2),
    new SquareBox(id = "","",false, List("171", "185"), 2),
    new SquareBox(id = "","",false, List("157", "158"), 2),
    new SquareBox(id = "","",false, List("158"), 1),
    new SquareBox(id = "","",false, List("142", "143"), 1),
    new SquareBox(id = "","",false, List("194", "195"), 1),
    new SquareBox(id = "","",false, List("193"), 2),
    new SquareBox(id = "","",false, List("186", "187"), 1),
    new SquareBox(id = "","",false, List("185", "187"), 3),
    new SquareBox(id = "","",false, List("172", "185"), 1),
    new SquareBox(id = "","",false, List("159", "172"), 1),
    new SquareBox(id = "","",false, List("159"), 2),
    new SquareBox(id = "","",false, List("159"), 1),
    new SquareBox(id = "","",false, List("173", "195"), 2),
    new SquareBox(id = "","",false, List("159", "160", "173"), 1),
    new SquareBox(id = "","",false, List("160"), 1),
    new SquareBox(id = "","",false, List("145", "160"), 0),
    new SquareBox(id = "","",false, List("161"), 1),
    new SquareBox(id = "","",false, List("161"), 1),
    new SquareBox(id = "","",false, List("161"), 1)
  )

  /*val listCircles = List[CircleBox](

  )*/

/*  val ex : SquareBox = listSquares.head

  println("before: " + ex.ID)
  ex.computeID()
  println("after: " + ex.ID)

  val ex2 : SquareBox = listSquares.filter(x => x.id == "X").head
  println(ex2)

  listSquares.map(x => x.computeID())

  val ex3 : SquareBox = listSquares.filter(x => x.id == "B").head

  println("after iterating: " + ex3.ID)*/

  listSquares.map(x => {
    x.computeID()
    println(x.ID)
  })

  /**
   * Increments a number by one
   * @param a number to be incremented
   * @return number incremented
   */
  def sum(a:Int) : Int = a + 1
}
